# Generated by Django 2.2.5 on 2019-09-28 17:29

import Users.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='society_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registration_number', models.CharField(max_length=20, null=True)),
                ('faculty_advisor', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.user',),
            managers=[
                ('objects', Users.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.user',),
            managers=[
                ('objects', Users.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registration_number', models.CharField(max_length=20)),
                ('batch', models.IntegerField(null=True)),
                ('program', models.CharField(max_length=80)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10)),
                ('dob', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('department', models.ForeignKey(limit_choices_to={'user_type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='faculty_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(max_length=80)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('department', models.ForeignKey(limit_choices_to={'user_type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
