# Generated by Django 2.2.5 on 2019-09-18 09:56

import Users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Users.manager.UserManager()),
            ],
        ),
    ]
