# Generated by Django 2.2.5 on 2019-09-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DEPARTMENT', 'Department'), ('SOCIETY', 'Society'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='STUDENT', max_length=15, verbose_name='user type'),
        ),
    ]
