# Generated by Django 2.2.5 on 2019-10-02 12:24

import Users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20190929_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.user',),
            managers=[
                ('objects', Users.manager.UserManager()),
            ],
        ),
    ]
