# Generated by Django 2.2.5 on 2019-09-24 22:49

import Users.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20190925_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.user',),
            managers=[
                ('objects', Users.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10, verbose_name='Gender'),
        ),
    ]
