# Generated by Django 2.2.5 on 2019-10-08 03:41

import Users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20191008_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='society',
            old_name='faculty_advisor',
            new_name='faculty_adviser',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that mobile already exists.'}, max_length=15, null=True, unique=True, validators=[Users.validators.MobileValidator()], verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and underscore only.', max_length=150, unique=True, validators=[Users.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
