# Generated by Django 2.2.5 on 2019-10-11 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20191008_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'SOCIETY'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='society_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
