# Generated by Django 2.2.5 on 2019-10-15 23:45

import Users.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20191011_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.user',),
            managers=[
                ('objects', Users.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DEPARTMENT', 'Department'), ('SOCIETY', 'Society'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student'), ('CHANNEL', 'Channel')], default='STUDENT', max_length=15, verbose_name='user type'),
        ),
    ]
