# Generated by Django 2.2.5 on 2019-09-11 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_notice', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=191)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('department', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'DEPARTMENT'}, related_name='notice_department', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
