# Generated by Django 2.2.5 on 2019-10-02 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_admin': False, 'user_type': 'DEPARTMENT'}, related_name='notice_department', to=settings.AUTH_USER_MODEL),
        ),
    ]
