# Generated by Django 2.2.5 on 2019-09-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='user_id',
            new_name='user',
        ),
    ]
