# Generated by Django 2.2.5 on 2019-10-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notice', '0002_auto_20191002_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
