# Generated by Django 2.2.5 on 2019-09-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notice', '0002_auto_20190918_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
